### ISSUE TITLE
does this work together with pt-feeder

### ISSUE THREAD

**Issue by daryledesilva** [bennettca/ProfitTrailer-new-binance-listings#1]

**Comment by ColeBennett** [comment]
It only modifies the trading/PAIRS.properties, not sure if pt-feeder overrides that in the different market settings.

**Comment by DavidLanz** [comment]
so run this command line first
java -jar ProfitTrailer-NBL.jar

then run Run-ProfitTrailer.cmd?

**Comment by DavidLanz** [comment]
do I need to restart Run-ProfitTrailer.cmd or leave it running?

**Comment by ColeBennett** [comment]
doesn't affect the actual profit trailer program, you just use that java -jar and keep it open in a terminal. PT could be on or off

**Comment by DavidLanz** [comment]
i saw you add line:

PIVXBTC_trading_enabled = false

can you make it 
PIVXBTC_sell_only_mode = true

cause maybe someone have buy it before, and need to sell them as soon as they can.

**Comment by ColeBennett** [comment]
that's a good idea, I can add it for a config option next update

**Comment by Shroomyhigh** [comment]
I am new to all of this so if you can please be half way decent to me. If I follow the instructions of the add-on will it help to not trade the newly added coins or did you actually fine that feeder rewrote it. I definitely don't want bags of true shit new coins. Is there a time limit before it would rip them from new coin status?

**Comment by ColeBennett** [comment]
Going to add feeder support soon it will modify all of the different market files. Also the NBL_days setting with NBL_clear = true will disable trading of the new coins until they are NBL_days old, then trading will activate for them again (if clear is true). Or just leave clear false so you can manually enable them if you decide they are good coins.

**Comment by daryledesilva** [comment]
thanks @bennettca keep up the good work! looking forward to the pt-feeder support

**Comment by Shroomyhigh** [comment]
So just so I am clear I should still do this anyways right now and then when the ptfeeder comes out do that one also. Where can I find online for binance where coins are  being delisted and new coins info, any clue?

**Comment by ColeBennett** [comment]
@Shroomyhigh They post them here https://support.binance.com/hc/en-us/sections/115000106672-New-Listings. Probably wait because ptfeeder overrides pairs.properties anyways I think.

**Comment by Shroomyhigh** [comment]
Tyvm

**Comment by mehtadone** [comment]
@bennettca you can either update all the market condition files or if you can write any new pairs in a text file somewhere, then I can read it and you can offset over it with feeder, eg stick it in SellOnlyMode, reduce buyvalue etc etc

**Comment by Deavall** [comment]
I'd like this to support Bittrex too if possible, great work!

**Comment by ColeBennett** [comment]
Added PT feeder support & adding a SOM option today. @mymatelee I can add Bittrex support but I don't know if there is a page where Bittrex lists the new coins.

**Comment by daryledesilva** [comment]
@bennettca @mehtadone of PTFeeder wants to connect with you! https://github.com/mehtadone/PTFeeder/issues/100#issuecomment-361491162

**Comment by daryledesilva** [comment]
thanks for the good job @bennettca closing this issue now
