### ISSUE TITLE
Add cmd file for newbs

### ISSUE THREAD

**Issue by ghost** [bennettca/ProfitTrailer-new-binance-listings#10]
[ProfitTrailer-Blacklist-Start.cmd.txt](https://github.com/bennettca/binance-auto-blacklist/files/1691817/ProfitTrailer-Blacklist-Start.cmd.txt)

**Comment by cryptomail2018** [comment]
full system crash after installing apps from you bennettca on Trailer V 1.2.6.14. 
cannot recover , deleted and done fresh installation and immediately goes on a uncontrollable SOM mode indefinately . 

please advice how to remove this part from system or stray files i might need to look for and delete to clear up system
