### ISSUE TITLE
Run in PM2 ?

### ISSUE THREAD

**Issue by ingeniumdesign** [bennettca/ProfitTrailer-new-binance-listings#11]
Hi, thanks for the nice Plugin.
I need to run the "java -jar ProfitTrailer-blacklist.jar" on the pi3, but my ProfitTrailer run in the PM2 Mode.
Can i run the blacklist in the PM2 too ?
command: "pm2 start ProfitTrailer-blacklist.jar" ?

or i dont need it?

thanks for help

**Comment by ingeniumdesign** [comment]
i add a new file: pm2-Blacklist.json
```json
{
  "apps": [
    {
      "name": "profit-trailer Blacklist",
      "cwd": ".",
      "script": "java",
      "args": [
        "-jar",
        "ProfitTrailer-blacklist.jar"
      ],
      "env": {
        "SPRING_PROFILES_ACTIVE": "prod"
      },
      "node_args": [],
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "exec_interpreter": "",
      "exec_mode": "fork",
	  "autorestart": false
    }
  ]
}
```

now i start the "pm2 start pm2-Blacklist.json"
=> "pm2 save"

is this code ok?

**Comment by Vicentewnunes** [comment]
That worked? Need to run it on a Ubuntu VPS..

**Comment by ingeniumdesign** [comment]
for me perfect!
