### ISSUE TITLE
Possible issue with som = true setting

### ISSUE THREAD

**Issue by tobizZL** [bennettca/ProfitTrailer-new-binance-listings#12]
Hey, there might be an issue with the som = true setting.

It always adds trading_enabled = false after sell_only_mode = true. Is this the correct behavior? I think just sell_only_mode = true would be enough and more safe?

Greetz

**Comment by coolmansr** [comment]
Try redownloading v1.0.3
It's fixed. (it's a reupload)

**Comment by tobizZL** [comment]
Oh, today?
Cause I downloaded it maybe 4 hours ago.
I will check it out.
Thx.

**Comment by jas-jas** [comment]
It's not fixed for me. I had some bags for some of the blacklisted coins and it added multiple entries to the end of my Pairs file in PT, so they went to WatchMode only. Can we confirm the fix is actually in the new release?
