### ISSUE TITLE
Raspberry Pi3 setup

### ISSUE THREAD

**Issue by cryptonz** [bennettca/ProfitTrailer-new-binance-listings#24]
I followed the Linux setup but how do i start the java file on rasbian OS?
thanks

**Comment by NathanHowell135** [comment]
in the cmd promt use 'java -jar ProfitTrailer-Blacklist.jar'
you will also need to make sure files are in your PT folder, and cd to that folder

**Comment by cryptonz** [comment]
Thank all good now..
