### ISSUE TITLE
Precedence of XXX_trading_enabled = false/true

### ISSUE THREAD

**Issue by HeebyGeeby** [bennettca/ProfitTrailer-new-binance-listings#4]
I'm running Blacklist (it's excellent), Feeder and PT. 
My PT pairs file has STEEMBTC_trading_enabled = false.
This is set by Feeder setting the market specific Pairs file. 

Later in the PT Pairs file, in the coin specific section, it has (from Feeder) STEEMBTC_trading_enabled = true. 

So the file has both STEEMBTC_trading_enabled = false and true.
Who wins? If the second entry wins, we have a problem.

**Comment by HeebyGeeby** [comment]
I can confirm this is a bug, in my case I just bought STEEM, second STEEMBTC_trading_enabled = true overrides the first.  
This shouldn't be relied on for Feeder.

**Comment by colinbrinton** [comment]
I can also confirm. I would recommend changing the implementation to sell_only_mode = true. This gives the added benefit of allowing bags to be sold off if a user is already holding a new coin.

**Comment by ColeBennett** [comment]
Yes, considering adding a sell only mode option. Also Feeder seems to overwrite every change blacklist does, there isn't really a way to fix this unless the Feeder devs allow it. I heard some people fixed the overwriting by setting interval to 1 minute though (if using feeder).

**Comment by colinbrinton** [comment]
EDIT: didn't see your updated code before I commented. Thanks so much for adding the feature! Great work! Very useful app.

@bennettca Your currently implementation works great with Feeder. It adds `XXXXXX_trading_enabled = false`  in all of the pair.txt files in the feeder. The feeder then adds `XXXXXX_trading_enabled = false` to the top of your Profit Trailer PAIRS.properties file. Manually adding `XXXXXX_sell_only_mode = true` in the Feeder pair.txt files has the same effect.

**Comment by ColeBennett** [comment]
Haven't used Feeder myself but that's good to see it actually works when editing pairs.txt!
