### ISSUE TITLE
Where is the blacklist.properties file mentioned in the read me?

### ISSUE THREAD

**Issue by dillonm1075** [bennettca/ProfitTrailer-new-binance-listings#5]

**Comment by HeebyGeeby** [comment]
File is created when you first run it. It has good defaults, just edit them if you need to.

**Comment by jas-jas** [comment]
https://github.com/bennettca/binance-auto-blacklist/releases/download/v1.0.3/ProfitTrailer-blacklist.jar  < I had a hard time finding this. 👍
