### ISSUE TITLE
Is there a manual/readme on how to install/use this?

### ISSUE THREAD

**Issue by alexdolli** [bennettca/ProfitTrailer-new-binance-listings#7]
As title says... not sure, how to use this.

**Comment by ColeBennett** [comment]
Yes read the usage section on the front page

**Comment by alexdolli** [comment]
Duh! Sorry man... and thanks for the great script!!

**Comment by alexdolli** [comment]
One more question. Once I edited the blacklist.properties file, do I need to restart the .jar file, or will it recognize the changes and update it automatically?

EDIT: Never mind, noticed it does update the files without restarting. Thanks again!
