### ISSUE TITLE
som = true bug

### ISSUE THREAD

**Issue by coolmansr** [bennettca/ProfitTrailer-new-binance-listings#8]
Hello,

when I set som = true in latest version, in PAIRS.properties i get:
IOSTBTC_sell_only_mode = false
shouldnt this be set to true?

thanks

**Comment by DavidLanz** [comment]
seems like a bug, reverse like this should be:

IOSTBTC_sell_only_mode = true

please update a new commit, tks!

**Comment by ColeBennett** [comment]
Fixed, re-download v1.0.3

**Comment by nmalancea** [comment]
@bennettca I think you need to repackage it as a new version. 1.0.3 does not contain your latest commit (https://github.com/bennettca/binance-auto-blacklist/commit/fb62a8faaa0f1d746573a10b909d154310c25f3d).

**Comment by coolmansr** [comment]
Fixed in v1.0.3
Thank you!

**Comment by jas-jas** [comment]
I just downloaded 1.0.3 and it put my "blacklisted coins" into WatchMode only.  So is this fixed or not?
