### ISSUE TITLE
Added Feature. Add delisting from other major exchanges

### ISSUE THREAD

**Issue by ghost** [bennettca/ProfitTrailer-new-binance-listings#9]
I believe a nice feature to add to this would be to select exchanges that you would like to query and if Coins are being delisted you can SOM, Disable, or modify DCA settings for the coins in your preferred exchange. 

Example is that FUN is being delisted in Brittex. It tanked yesterday due to this. Because of this you could have the pairs files updated for Binance to only do SOM, or Disable Trading, or Change DCA settings due to this.

**Comment by ghost** [comment]
Here is Brittex delisting.
https://support.bittrex.com/hc/en-us/sections/200560334-Coin-Removals

**Comment by daryledesilva** [comment]
+1 for Bittrex support!
